# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
	{
		:name => "ignite-node1",
		:eth1 => "192.168.6.10",
		:mem => "1536",
		:cpu => "1",
		:box => "ubuntu/trusty64",
		:shells => [
			"shells/system/copydebs.sh",
			"shells/system/aptupdate.sh",
			"shells/system/apt.sh",
			"shells/system/generic.sh"			
		],
		:files => [
		{ 
			:src => "files/resources/archives.zip", 
			:dst => "/home/vagrant/archives.zip" },
		{ 
			:src => "files/resources/apache-ignite-fabric-1.9.0-bin.zip", 
			:dst => "/home/vagrant/ignite.zip" },
		],
		:ports_forward => [ { :name => "grafana", :guest => "3000", :host => "3011" } ]
	}
]


Vagrant.configure(2) do |config|
    boxes.each do |opts|

        config.vm.define opts[:name] do |config|
            config.vbguest.auto_update = false
            config.vm.provider "virtualbox" do |v, override|
                override.vm.box = opts[:box]
            end
            config.vm.hostname = opts[:name]
            config.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
            end

            config.vm.network :private_network, ip: opts[:eth1]
			
			opts[:ports_forward].each do |item|
                config.vm.network "forwarded_port", guest: item[:guest], host: item[:host], host_ip: "127.0.0.1"
            end

            opts[:files].each do |fileitem|
                config.vm.provision :file do |file|
                    file.source = fileitem[:src]
                    file.destination = fileitem[:dst]
                end
            end
            opts[:shells].each do |item|
                config.vm.provision :shell, path: item
            end
        end
    end
end
